# Generated by Django 5.0.4 on 2024-05-09 20:37

import colorfield.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integracje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=100)),
                ('zdjecie', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kolor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Templatki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('zdjecia', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ustawienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_templatki_sklep', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cena_templatki_sklep_dostosowanie', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cena_templatki_wrapbootstrap', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cena_customowej_templatki', models.DecimalField(decimal_places=2, max_digits=11)),
                ('email_kontaktowy', models.EmailField(max_length=254)),
                ('tel_kontaktowy', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('opis', models.CharField(max_length=500)),
                ('templatka', models.ImageField(upload_to='')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=11)),
                ('email', models.EmailField(max_length=254)),
                ('uwagi_do_templatki', models.CharField(max_length=500)),
                ('plik', models.FileField(upload_to=None)),
                ('inne_uwagi', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=40)),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formwizard.zamowienie')),
            ],
        ),
    ]
