# Generated by Django 5.0.6 on 2024-06-03 19:01

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formwizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=500)),
                ('template', models.ImageField(upload_to='')),
                ('sum_to_pay', models.DecimalField(decimal_places=2, max_digits=11)),
                ('email', models.EmailField(max_length=254)),
                ('template_type', models.CharField(max_length=100)),
                ('template_comments', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to=None)),
                ('other_comments', models.CharField(max_length=500)),
                ('integrations', models.ManyToManyField(to='formwizard.integration')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=40)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formwizard.order')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('price_template_shop', models.DecimalField(decimal_places=2, max_digits=11)),
                ('price_template_shop_adjustment', models.DecimalField(decimal_places=2, max_digits=11)),
                ('price_template_wrapbootstrap', models.DecimalField(decimal_places=2, max_digits=11)),
                ('price_custom_template', models.DecimalField(decimal_places=2, max_digits=11)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('key_for_paying', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('link', models.URLField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Kolor',
            new_name='Color',
        ),
        migrations.DeleteModel(
            name='Integracje',
        ),
        migrations.RemoveField(
            model_name='platnosc',
            name='zamowienie',
        ),
        migrations.DeleteModel(
            name='Templatki',
        ),
        migrations.DeleteModel(
            name='Ustawienia',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='addcolor',
        ),
        migrations.DeleteModel(
            name='Platnosc',
        ),
        migrations.DeleteModel(
            name='Zamowienie',
        ),
    ]
