name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install pylint-django[with-django]
    - name: Analysing the code with pylint
      run: |
        pylint --load-plugins pylint_django --django-settings-module=shopwizard.settings --disable=missing-function-docstring,missing-module-docstring,missing-class-docstring ./shopwizard/formwizard/views.py ./shopwizard/formwizard/forms.py ./shopwizard/formwizard/models.py
